ci:
    autofix_prs: true
    autoupdate_schedule: weekly
repos:

- repo: https://github.com/DanielNoord/pydocstringformatter
  rev: v0.7.3
  hooks:
    - id: pydocstringformatter
      args: [
        "--style {numpydoc,pep257}",
        "--no-strip-whitespace",
        "--no-capitalize-first-letter",
      ]

- repo: https://github.com/numpy/numpydoc
  rev: v1.6.0
  hooks:
  - id: numpydoc-validation
    files: ^src/pvgmsh/

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.13
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format

- repo: https://github.com/scientific-python/cookie
  rev: 2023.12.21
  hooks:
    - id: sp-repo-review
      additional_dependencies: ["repo-review[cli]"]
      args: ["--ignore=PY,PP,PC", "--show=errskip"]
