[build-system]
requires = [
  'gmsh==4.12.1',
  'meshio==5.3.4',
  'pygmsh==7.1.17',
  'pyvista==0.43.2',
  'setuptools',
]
build-backend = 'setuptools.build_meta'

[project]
name = "pvgmsh"
dynamic = ['version']
dependencies = [
  'gmsh==4.12.1',
  'meshio==5.3.4',
  'pygmsh==7.1.17',
  'pyvista==0.43.2',
]

[tool.setuptools.dynamic]
version = {attr = 'pvgmsh.__version__'}

[tool.numpydoc_validation]
checks = [
    "all",  # all but the following:
    "GL01",  # Contradicts numpydoc examples
    "GL02",  # Permit a blank line after the end of our docstring
    "GL03",  # Considering enforcing
    "GL09",  # Deprecation warning should precede extended summary (check broken)
    "SA01",  # Not all docstrings need a see also
    "SA04",  # See also section does not need descriptions
    "SS05",  # Appears to be broken.
    "ES01",  # Not all docstrings need an extend summary.
    "EX01",  # Examples: Will eventually enforce
    "YD01",  # Yields: No plan to enforce
]

[tool.ruff]
line-length = 150
target-version = "py38"
src = ["src"]

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "COM812",
    "D203",
    "D212",
    "ISC001",
]

[tool.ruff.format]
docstring-code-format = true

[tool.repo-review]
ignore = ["PY", "PP", "MY"]

[tool.mypy]
ignore_missing_imports = true
