[build-system]
requires = [
  'gmsh',
  'meshio',
  'numpy',
  'pyvista',
  'setuptools',
]
build-backend = 'setuptools.build_meta'

[project]
name = "pyvista-gmsh"
dynamic = ['version']
dependencies = [
  'gmsh',
  'meshio',
  'numpy',
  'pyvista',
]

[tool.setuptools.dynamic]
version = {attr = 'pvgmsh.__version__'}

[tool.numpydoc_validation]
checks = [
    "all",  # all but the following:
    "GL01",  # Contradicts numpydoc examples
    "GL02",  # Permit a blank line after the end of our docstring
    "GL03",  # Considering enforcing
    "GL09",  # Deprecation warning should precede extended summary (check broken)
    "SA01",  # Not all docstrings need a see also
    "SA04",  # See also section does not need descriptions
    "SS05",  # Appears to be broken.
    "ES01",  # Not all docstrings need an extend summary.
    "EX01",  # Examples: Will eventually enforce
    "YD01",  # Yields: No plan to enforce
]

[tool.ruff]
line-length = 150

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "D203",
    "D212",
]

[tool.ruff.format]
docstring-code-format = true
